### ISSUE TITLE
feat: Add Stencil to Wappalyzer for tracking in HTTPArchive

### ISSUE THREAD

**Issue by justinfagnani** [ionic-team/stencil#3252]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

[Wappalyzer](https://github.com/AliasIO/wappalyzer) is a library that detects various technology usage on web sites. It's in turn used to add JS library usage metadata to HTTPArchive. To fairly track Stencil usage on public websites it should be added to Wappalyzer's library detection.

### Describe the Use Case

To show up in HTTPArchive-based reports like the Web Almanac and https://github.com/GoogleChromeLabs/perf-track

### Additional Information

Wappalyzer detection runs as a browser extension. It can look at the DOM or JS expressions. Library detection is declarative and it should be pretty easy to detect Stencil if there's some kind of global variable that indicates that Stencil is loaded.

**Comment by rwaskiewicz** [comment]
This appears to have been completed as a part of https://github.com/wappalyzer/wappalyzer/pull/6557.
