### ISSUE TITLE
[Tracking] WebdriverIO Migration

### ISSUE THREAD

**Issue by christian-bromann** [ionic-team/stencil#5458]
In #5456 we introduced WebdriverIO as testing framework of choice for testing Stencil components. This issue tracks our progress migrating our current existing Karma test suite to WebdriverIO. To migrate a test, follow these instructions:

1. assign a test to you by clicking on the checkbox next to the test you like to migrate
1. move the whole directory to the `wdio` folder, e.g. `git mv test/karma/test-app/conditional-rerender test/wdio/conditional-rerender`
1. rename `karma.spec.ts` into e.g. `cmp.test.tsx` (note the __.tsx__)
1. replace the component test up by using WebdriverIOs `render` function, e.g. 
    ```tsx
    import { h, Fragment } from '@stencil/core';
    import { render } from '@wdio/browser-runner/stencil';

    describe('conditional-rerender', function () {
      beforeEach(() => {
        render({
          template: () => <>...</>
        })
      })
    })
    ```
    Copy everything from the included `.html` file , except doctype, meta and script tags that import the test app:
    ```patch
    - <!DOCTYPE html>
    - <meta charset="utf8">
    - <script src="./build/testapp.esm.js" type="module"></script>
    - <script src="./build/testapp.js" nomodule></script>
    ```
1. run the test in watch mode to modify it, e.g. `cd test/wdio && npm ci && npm run build && npm run wdio -- --spec conditional-rerender --watch`
1. Make updates to the test
    - if you see `querySelector` calls, replace them with WebdriverIO queries, e.g.
       ```patch
       - const main = app.querySelector('main');
       + const main = $('main');
       ```
    - either replace all synchronous assertions with asynchronous ones provided by WebdriverIO or ensure that the component is ready for assertion by adding a `await main.waitForExist()` after every time you call `render` or interact with the component via `click`
    - use the chance to optimize assertions e.g. by consolidating them into a `toMatchInlineSnapshot`
1. Lastly, remove the `.html` file from the directory and other unnecessary files
1. Run the whole test suite from the root directory via: `npm run test.wdio`
1. Build Karma to compile updated types for its testapp `cd test/karma && npm run build.all`
1. Run Prettier to ensure formatting is alright: `npm run prettier`
1. If all passes, raise a PR, move to the next test and start from the beginning.

Tests:

- [x] [`conditional-rerender`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/conditional-rerender)
- [x] [`css-variables`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/css-variables)
- [x] [`custom-elements-delegates-focus`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-elements-delegates-focus)
- [x] [`custom-elements-output-tag-class-different`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-elements-output-tag-class-different)
- [x] [`custom-elements-output-webpack`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-elements-output-webpack)
- [x] [`custom-event`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/custom-event)
- [x] [`delegates-focus`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/delegates-focus)
- [x] [`dom-reattach`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/dom-reattach)
- [x] [`dom-reattach-clone`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/dom-reattach-clone)
- [x] [`dynamic-css-variables`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/dynamic-css-variables)
- [x] [`dynamic-imports`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/dynamic-imports)
- [x] [`es5-addclass-svg`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/es5-addclass-svg)
- [x] [`esm-import`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/esm-import)
- [x] [`esm-webpack`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/esm-webpack)
- [x] [`event-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/event-basic)
- [x] [`event-custom-type`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/event-custom-type)
- [x] [`event-listener-capture`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/event-listener-capture)
- [x] [`external-imports`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/external-imports)
- [x] [`form-associated`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/form-associated)
- [x] [`global-script`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/global-script)
- [x] [`global.ts`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/global.ts)
- [x] [`host-attr-override`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/host-attr-override)
- [x] [`import-aliasing`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/import-aliasing)
- [x] [`init-css-shim`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/init-css-shim)
- [x] [`input-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/input-basic)
- [x] [`invisible-prehydration-false`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/invisible-prehydration-false)
- [x] [`json-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/json-basic)
- [x] [`key-reorder`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/key-reorder)
- [x] [`lifecycle-async`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/lifecycle-async)
- [x] [`lifecycle-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/lifecycle-basic)
- [x] [`lifecycle-nested`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/lifecycle-nested)
- [x] [`lifecycle-unload`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/lifecycle-unload)
- [x] [`lifecycle-update`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/lifecycle-update)
- [x] [`listen-jsx`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/listen-jsx)
- [x] [`listen-reattach`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/listen-reattach)
- [x] [`listen-window`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/listen-window)
- [x] [`node-resolution`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/node-resolution)
- [x] ~~[`noscript.js`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/noscript.js)~~ no test, just a file
- [x] [`prerender-test`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/prerender-test)
- [x] [`reflect-nan-attribute`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/reflect-nan-attribute)
- [x] [`reflect-nan-attribute-hyphen`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/reflect-nan-attribute-hyphen)
- [x] [`reflect-nan-attribute-with-child`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/reflect-nan-attribute-with-child)
- [x] [`reflect-single-render`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/reflect-single-render)
- [x] [`reflect-to-attr`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/reflect-to-attr)
- [x] [`remove-child-patch`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/remove-child-patch)
- [x] [`reparent-style`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/reparent-style)
- [x] [`scoped-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-basic)
- [x] [`scoped-conditional`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-conditional)
- [x] [`scoped-slot-append-and-prepend`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-slot-append-and-prepend)
- [x] [`scoped-slot-child-insert-adjacent`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-slot-child-insert-adjacent)
- [x] [`scoped-slot-in-slot`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-slot-in-slot)
- [x] [`scoped-slot-text`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-slot-text)
- [x] [`scoped-slot-text-with-sibling`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/scoped-slot-text-with-sibling)
- [x] [`shadow-dom-array`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/shadow-dom-array)
- [x] [`shadow-dom-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/shadow-dom-basic)
- [x] [`shadow-dom-mode`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/shadow-dom-mode)
- [x] ~~[`shadow-dom-slot-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/shadow-dom-slot-basic)~~ (removed)
- [x] [`shadow-dom-slot-nested`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/shadow-dom-slot-nested)
- [x] [`shared-jsx`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/shared-jsx)
- [x] [`slot-array-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-array-basic)
- [x] [`slot-array-complex`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-array-complex)
- [x] [`slot-array-top`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-array-top)
- [x] [`slot-basic`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-basic)
- [x] [`slot-basic-order`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-basic-order)
- [x] [`slot-children`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-children)
- [x] [`slot-dynamic-name-change`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-dynamic-name-change)
- [x] [`slot-dynamic-wrapper`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-dynamic-wrapper)
- [x] [`slot-fallback`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-fallback)
- [x] [`slot-hide-content`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-hide-content)
- [x] [`slot-html`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-html)
- [x] [`slot-light-dom`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-light-dom)
- [x] [`slot-map-order`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-map-order)
- [x] [`slot-nested-default-order`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-nested-default-order)
- [x] [`slot-nested-order`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-nested-order)
- [x] [`slot-ng-if`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-ng-if)
- [x] [`slot-no-default`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-no-default)
- [x] [`slot-parent-tag-change`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-parent-tag-change)
- [x] [`slot-reorder`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-reorder)
- [x] [`slot-replace-wrapper`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-replace-wrapper)
- [x] [`slot-scoped-list`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-scoped-list)
- [x] [`slot-shadow-list`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slot-shadow-list)
- [x] [`slotted-css`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/slotted-css)
- [x] [`static-members`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/static-members)
- [x] [`static-styles`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/static-styles)
- [x] [`stencil-sibling`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/stencil-sibling)
- [x] [`svg-attr`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/svg-attr)
- [x] [`svg-class`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/svg-class)
- [x] [`tag-names`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/tag-names)
- [x] [`text-content-patch`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/text-content-patch)
- [x] [`watch-native-attributes`](https://github.com/ionic-team/stencil/blob/b4230b6939b016299d78cc4d16c175e73c703733/test/karma/test-app/watch-native-attributes)
- [x] slot-conditional-rendering (migrated with https://github.com/ionic-team/stencil/pull/5403/commits/240d24d0f50a94782414f57602ced3565f6ba7b7)
- [x] slot-ref (migrated with https://github.com/ionic-team/stencil/pull/5403/commits/240d24d0f50a94782414f57602ced3565f6ba7b7)
- [x] slot-nested-dynamic (implemented with https://github.com/ionic-team/stencil/pull/5403/commits/240d24d0f50a94782414f57602ced3565f6ba7b7) (RYAN: This gets added in an unlanded PR - https://github.com/ionic-team/stencil/pull/5403)

**Comment by yigityuce** [comment]
these three is missing in the checklist, would be good to add them as done

- slot-conditional-rendering (moved with https://github.com/ionic-team/stencil/pull/5403/commits/240d24d0f50a94782414f57602ced3565f6ba7b7)
- slot-ref (moved with https://github.com/ionic-team/stencil/pull/5403/commits/240d24d0f50a94782414f57602ced3565f6ba7b7)
- slot-nested-dynamic (implemented with https://github.com/ionic-team/stencil/pull/5403/commits/240d24d0f50a94782414f57602ced3565f6ba7b7)

**Comment by rwaskiewicz** [comment]
Closing, migration of the tests themselves is complete (save for a few misc cleanup items). Great job everyone 🎉
